print('Tuples are like lists but we cannot change tuples after created')
tuple1=(5,6,7,8)
tupletolist = list(tuple1)
listtotuple=tuple(tupletolist)
print('Tuple:',tuple1)
print('Tuple To List',tupletolist)
print('List To Tuple',listtotuple)
print('Length of Tuple:',len(tuple1))
print('Min of Tuple:',min(tuple1))
print('Max of Tuple:',max(tuple1))